baseURL = 'https://interfacecraft.online'
languageCode = 'en-us'
title = 'Visual AI Artist: Alexander Deplov'

# Important: Define which sections should appear on the homepage
[params]
  mainSections = ["posts", "portfolio"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allows raw HTML in Markdown
  [markup.highlight]
    style = "onedark"  # Syntax highlighting style
    lineNos = false    # No line numbers
