baseURL = 'https://alexdeplov.github.io/'
languageCode = 'en-us'
title = "Alexander Deplov – Senior Product Designer Blog"
theme = 'paper'
paginate = 100

[taxonomies]
tag = "tags"

[params]
  color = 'linen'
  mastodon = 'https://mastodon.social/@alex_deplov'
  rss = true

# home page profile
  avatar = 'https://gravatar.com/avatar/7a371a2fef36b02d83ee5e65f9a7721d?size=256&cache=1718741543588'                 # gravatar email or image url
  name = ' '
  bio = "I'm senior product designer at Slumber Studios. Solving problems creatively. Co-founder of Pleeq Software. ADPList design mentor. AI prompt curator on Pinterest. FreeBSD hobbyist."

# misc
  disableHLJS = false                       # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  #gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  #favicon = "favicon.ico"                   # customize the default favicon
  #appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon


  [module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"